
package ar.edu.ubp.das.ws.jaxws;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;

/**
 * This class was generated by Apache CXF 3.5.6
 * Tue Oct 08 20:22:43 ART 2024
 * Generated source version: 3.5.6
 */

@XmlRootElement(name = "getProveedorInfo", namespace = "http://ws.das.ubp.edu.ar/")
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "getProveedorInfo", namespace = "http://ws.das.ubp.edu.ar/")

public class GetProveedorInfo {


}

