
package ar.edu.ubp.das.ws.jaxws;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;

/**
 * This class was generated by Apache CXF 3.5.6
 * Mon Oct 07 17:34:30 ART 2024
 * Generated source version: 3.5.6
 */

@XmlRootElement(name = "AuthenticationException", namespace = "http://naming.javax/")
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "AuthenticationException", namespace = "http://naming.javax/", propOrder = {"explanation", "message", "remainingName", "resolvedName", "resolvedObj", "rootCause"})

public class AuthenticationExceptionBean {

    private java.lang.String explanation;
    private java.lang.String message;
    private javax.naming.Name remainingName;
    private javax.naming.Name resolvedName;
    private java.lang.Object resolvedObj;
    private java.lang.Throwable rootCause;

    public java.lang.String getExplanation() {
        return this.explanation;
    }

    public void setExplanation(java.lang.String newExplanation)  {
        this.explanation = newExplanation;
    }

    public java.lang.String getMessage() {
        return this.message;
    }

    public void setMessage(java.lang.String newMessage)  {
        this.message = newMessage;
    }

    public javax.naming.Name getRemainingName() {
        return this.remainingName;
    }

    public void setRemainingName(javax.naming.Name newRemainingName)  {
        this.remainingName = newRemainingName;
    }

    public javax.naming.Name getResolvedName() {
        return this.resolvedName;
    }

    public void setResolvedName(javax.naming.Name newResolvedName)  {
        this.resolvedName = newResolvedName;
    }

    public java.lang.Object getResolvedObj() {
        return this.resolvedObj;
    }

    public void setResolvedObj(java.lang.Object newResolvedObj)  {
        this.resolvedObj = newResolvedObj;
    }

    public java.lang.Throwable getRootCause() {
        return this.rootCause;
    }

    public void setRootCause(java.lang.Throwable newRootCause)  {
        this.rootCause = newRootCause;
    }

}

